"""cl9 init script example — rename this file to init.py and uncomment what you need.

This file is re-generated by `cl9 init --force` and is safe to delete.
init.py (if it exists) is never touched by cl9.

See ADR 0009 and the cl9.agent module for the full API reference.

Entry point: cl9 agent spawn [--name NAME] [--profile PROFILE]
"""

import subprocess  # noqa: F401

from cl9 import agent  # noqa: F401

# ---------------------------------------------------------------------------
# Secrets / credentials
# ---------------------------------------------------------------------------

# Pull an API key from 1Password and inject it into the agent environment:
# agent.env["ANTHROPIC_API_KEY"] = subprocess.check_output(
#     ["op", "read", "op://Personal/Anthropic/credential"], text=True
# ).strip()

# Or use an AWS profile for Bedrock access:
# agent.env["AWS_PROFILE"] = "my-bedrock-profile"

# ---------------------------------------------------------------------------
# MCP server configuration
# ---------------------------------------------------------------------------

# Inject a token into an MCP server that was already declared in the profile:
# agent.mcp.setdefault("mcpServers", {}).setdefault("my-server", {}).setdefault(
#     "env", {}
# )["MY_TOKEN"] = "secret"

# ---------------------------------------------------------------------------
# Claude settings overrides
# ---------------------------------------------------------------------------

# Override the model for this project:
# agent.settings["model"] = "claude-opus-4-5"
